### ISSUE TITLE
error: type 'Bundle' has no member 'module'

### ISSUE THREAD

**Issue by SusanDoggie** [swiftlang/swift-source-compat-suite#1049]
**Description**
error: type 'Bundle' has no member 'module'

This error only occurs in swift 5.9-dev

refs: 
https://github.com/apple/swift-source-compat-suite/pull/747
https://ci.swift.org/job/swift-PR-source-compat-suite-test-macOS/122/artifact/swift-source-compat-suite/FAIL_Doggie_5.7_BuildSwiftPackage.log

**Expected behavior**
Build success

**Environment**
swift 5.9-dev

**Comment by AnthonyLatsis** [comment]
I am transferring this retroactively just to tidy things up.
